### ISSUE TITLE
ps fails to install from source on Big Sur, impossible to install in a renv (v. 0.13) project

### ISSUE THREAD

**Issue by mbac** [r-lib/ps#108] opened 2021-03-03 22:49 UTC
Hi,

I keep getting an error installing `ps` in a project where I'm also using `renv` (latest version as of writing.) This is the error on macOS Big Sur (Xcode and Xcode command line tools installed), using RStudio 1.4.1103:

```r
> install.packages("ps")
Retrieving 'https://cran.rstudio.com/src/contrib/ps_1.6.0.tar.gz' ...
	OK [file is up to date]
Installing ps [1.6.0] ...
	FAILED
Error installing package 'ps':
==============================

* installing to library ‘/Users/marco/Downloads/PyhonPlot-Week3/renv/staging/1’
* installing *source* package ‘ps’ ...
** package ‘ps’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/opt/llvm/bin/clang -fopenmp -g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe -Wall px.c -o px
ld: library not found for -lomp
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [px] Error 1
ERROR: compilation failed for package ‘ps’
* removing ‘/Users/marco/Downloads/PyhonPlot-Week3/renv/staging/1/ps’
Error: install of package 'ps' failed [error code 1]
---
```

I get the same error when I open a non-`renv` project and try to install from source. If I select to install the package binary, it works fine. I'm not getting a prompt to choose installation method while using `renv`.

Thanks for any help you can give!

**Comment by gaborcsardi** [comment] 2021-03-04 09:14
This seems like a duplicate of #56, #81, etc.

**Comment by mbac** [comment] 2021-03-04 15:10
Hi,

I've tried reinstalling R from the CRAN installer (_vs._ `homebrew`), as per #56, and I do have the latest Xcode.app installed (per #81). Still, no dice. I do understand it's not a `ps` bug per se, but I wonder if there might be an interaction with `renv` and if you have suggestions for troubleshooting.

**Comment by gaborcsardi** [comment] 2021-03-04 15:15
`/usr/local/opt/llvm/bin/clang` is not XCode. What version of R is this? 

I don't think renv has much to do with this, probably this fails as well, without renv:
```
install.packages("ps", type = "source")
```

**Comment by mbac** [comment] 2021-03-04 15:20
You're right, I'm getting the same error.

The current R version (the one from CRAN) is 4.0.4. Full `Sys.env()` [here](https://gist.github.com/mbac/715fd7b5a6712eb8793c55ff771d7343)…

**Comment by gaborcsardi** [comment] 2021-03-04 15:29
The environment variables are not relevant here, I think. `R CMD config CC` prints the C compiler R uses, this is mine:
```
❯ R CMD config CC
clang -mmacosx-version-min=10.13
```

`/usr/local/opt/llvm/bin/clang` is most likely not xcode, so find out why you use that compiler.... and possibly update the config to remove `-fopenmp`.

**Comment by gaborcsardi** [comment] 2021-03-04 15:30
You might get better luck asking on the `R-sig-mac` mailing mailing list or at `R-pkg-devel` or at RStudio community.

**Closed** 2021-03-04 19:42 UTC
