### ISSUE TITLE
Long command lines cause parsing issue 

### ISSUE THREAD

**Issue by xhochy** [r-lib/ps#82] opened 2020-05-04 16:16 UTC
In `psll__parse_stat_file`, the library tries to parse `/proc/<pid>/stat` and relies in this parsing that the command is wrapped in parentheses. With long filenames on some platforms (I could only reproduce this on ppc64le, not x86) the command gets truncated. The code in https://github.com/r-lib/ps/blob/2a4334ef5f8aa45aecc5bc2e181bfb82c59f6769/src/api-linux.c#L198-L204 cannot handle this case.
 
Running 

```r
> library(processx)
```

results in 
```
Error: package or namespace load failed for ‘processx’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: NULL
  error: Cannot parse stat file
Execution halted
```

The `/proc/<pid>/stat` output is as follows:

```
> readLines('/proc/6139/stat')
[1] "6139 (/home/conda/feedstock_root/build_artifacts/r-processx_1588605077356/_h_env_placehold_placehold_placehold_placehold_placehold_p0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 274886397616 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
```

**Comment by gaborcsardi** [comment] 2020-05-05 10:52
Thanks!

**Comment by gaborcsardi** [comment] 2020-09-30 13:40
I can't reproduce this on ppc64le, actually. For a long file name the stat line looks like this:
```
gabor@power:~$ cat /proc/1721/stat
1721 (123456789012345) S 1697 1721 1246 58624 1754 1077936128 84 0 0 0 0 3 0 0 20 0 1 0 57955 6422528 22 18446744073709551615 4679480901632 4679480951984 140737414995616 0 0 0 0 0 0 1 0 0 17 1 0 0 0 0 0 4679481031248 4679481032936 4680146681856 140737415019692 140737415019799 140737415019799 140737415020433 0
```

Linux version:
```
gabor@power:~$ uname -a
Linux power 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:13 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
```

I am not too excited about working around this in ps, because your example looks nothing like a `stat` file should look, way too many zeros there, where some values cannot be zeros.

**Comment by xhochy** [comment] 2020-09-30 13:45
I didn't do any modifications to the output, this is how it was reported to me. In my testing setup I run the code though in `docker-qemu` where the host system is x86 but only the CentOS 7 in the container is `ppc64le`.

**Comment by gaborcsardi** [comment] 2020-09-30 13:51
I understand. Although it is possible that `readLines()` could not read it properly. In the manual (https://man7.org/linux/man-pages/man5/proc.5.html) it is clearly documented that there must be a closing paren there. 

Maybe this is a redhat/centos feature? Can you reproduce it, without R, just by creating an executable with a long name?

**Comment by gaborcsardi** [comment] 2020-10-05 09:13
I am closing this, as I have to way to reproduce it. If you manage to reproduce it, please re-open it.

**Closed by gaborcsardi** 2020-10-05 09:13 UTC
Labels: bug, reprex
